/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ias4g
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbPrincipal = new javax.swing.JMenuBar();
        mnuProducts = new javax.swing.JMenu();
        itmUpdate = new javax.swing.JMenuItem();
        itmCreate = new javax.swing.JMenuItem();
        itmDelete = new javax.swing.JMenuItem();
        itmReports = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmExit = new javax.swing.JMenuItem();
        mnuClients = new javax.swing.JMenu();
        mnuEmployee = new javax.swing.JMenu();
        mnuAdm = new javax.swing.JMenu();
        itmChangeUserPass = new javax.swing.JMenuItem();
        itmDeleteUser = new javax.swing.JMenuItem();
        itmDeleteAllUser = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do sistema");
        setMaximumSize(new java.awt.Dimension(530, 380));
        setMinimumSize(new java.awt.Dimension(530, 380));
        setName("jfDashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(530, 380));
        getContentPane().setLayout(null);

        mnuProducts.setText("Produtos");

        itmUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmUpdate.setText("Alterar");
        mnuProducts.add(itmUpdate);

        itmCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCreate.setText("Cadastrar");
        mnuProducts.add(itmCreate);

        itmDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmDelete.setText("Excluir");
        mnuProducts.add(itmDelete);

        itmReports.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmReports.setText("Relatórios");
        mnuProducts.add(itmReports);
        mnuProducts.add(jSeparator1);

        itmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExit.setText("Sair");
        mnuProducts.add(itmExit);

        jmbPrincipal.add(mnuProducts);

        mnuClients.setText("Clientes");
        jmbPrincipal.add(mnuClients);

        mnuEmployee.setText("Funcionários");
        jmbPrincipal.add(mnuEmployee);

        mnuAdm.setText("Admin");

        itmChangeUserPass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itmChangeUserPass.setText("Alterar Senha de Usuário");
        mnuAdm.add(itmChangeUserPass);

        itmDeleteUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itmDeleteUser.setText("Excluir Usuário");
        mnuAdm.add(itmDeleteUser);

        itmDeleteAllUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itmDeleteAllUser.setText("Excluir Todos os Usuários");
        mnuAdm.add(itmDeleteAllUser);

        jmbPrincipal.add(mnuAdm);

        mnuHelp.setText("Ajuda");
        jmbPrincipal.add(mnuHelp);

        setJMenuBar(jmbPrincipal);

        setSize(new java.awt.Dimension(546, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmChangeUserPass;
    private javax.swing.JMenuItem itmCreate;
    private javax.swing.JMenuItem itmDelete;
    private javax.swing.JMenuItem itmDeleteAllUser;
    private javax.swing.JMenuItem itmDeleteUser;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmReports;
    private javax.swing.JMenuItem itmUpdate;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenu mnuAdm;
    private javax.swing.JMenu mnuClients;
    private javax.swing.JMenu mnuEmployee;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuProducts;
    // End of variables declaration//GEN-END:variables
}
