SELECT      -- LISTA DE CAMPOS PARA PROJEÇÃO
FROM        -- NOMES DA TABELAS
WHERE       -- FIÇTRA LIMHAS NA TABELA ANTES DE AGRUPAR
GROUP BY    -- AGRUPA AS LINHAS RESULTANDTES
HAVING      -- FILTRA LINHAS APÓS AGRUPAR
ORDER BY    -- ORDENA/CLASSIFICA AS LINHAS RESULTANTES

