SELECT      -- LISTA DE CAMPOS PARA PROJEÇÃO.
FROM        -- NOMES DA TABELAS.
ON          -- COLUNAS QUE ESTABELECEM A JUNÇÃO.
WHERE       -- FIÇTRA LIMHAS NA TABELA ANTES DE AGRUPAR.
GROUP BY    -- AGRUPA AS LINHAS RESULTANDTES.
HAVING      -- FILTRA LINHAS APÓS AGRUPAR.
ORDER BY    -- ORDENA/CLASSIFICA AS LINHAS RESULTANTES.

-- ######################### INNER JOIN #########################

SELECT  CODFILME, TITULO DESCRICAO
FROM    FILME INNER JOIN CATEGORIA
ON      FILME.CODCATEG = CATEGOARIA.CODCATEG

SELECT  EMPNO, ENAME, EMP.DEPTNO, DEPT.DEPTNO, DNAME, LOC
FROM    EMP INNER JOIN DEPT
ON      EMP.DEPTNO = DEPT.DEPTNO

SELECT  EMPNO, ENAME, EMP.DEPTNO, DEPT.DEPTNO, DNAME, LOC
FROM    EMP INNER JOIN DEPT
ON      EMP.DEPTNO = DEPT.DEPTNO
WHERE   EMP.DEPT = IN (10,20)

-- ######################### INNER JOIN #########################