SELECT      -- LISTA DE CAMPOS PARA PROJEÇÃO.
FROM        -- NOMES DA TABELAS.
ON          -- COLUNAS QUE ESTABELECEM A JUNÇÃO.
WHERE       -- FIÇTRA LIMHAS NA TABELA ANTES DE AGRUPAR.
GROUP BY    -- AGRUPA AS LINHAS RESULTANDTES.
HAVING      -- FILTRA LINHAS APÓS AGRUPAR.
ORDER BY    -- ORDENA/CLASSIFICA AS LINHAS RESULTANTES.

SELECT  CODFILME, TITULO DESCRICAO
FROM    FILME INNER JOIN CATEGORIA
ON      FILME.CODCATEG = CATEGOARIA.CODCATEG

