# @name create-prompt
POST http://localhost:3333/prompts
Content-Type: application/json

{
  "title": "Spotify",
  "template": "Spotify description"
}

###

# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="Teologia-1m.mp3"
Content-Type: audio/mpeg

< C:\Users\Izael Silva\Music\Teologia-1m.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/730c4103-6b30-4d11-8246-5911b33e10a9/transcription
Content-Type: application/json

{
  "prompt": "Vida cristã, Trabalho, Deus, reflexão"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete 
Content-Type: application/json

{
  "videoId": "730c4103-6b30-4d11-8246-5911b33e10a9",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''"
}